//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eje.pro5webApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class entidad
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Primer_apellido { get; set; }
        public string Segundo_apellido { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        public string clave { get; set; }
    }
}
